export type Locale = "ru" | "en";

export const content = {
  ru: {
    locale: "ru",
    path: "/",
    alternatePath: "/en/",
    seo: {
      title: "Психолог Наталья в Ростове-на-Дону | Очно и онлайн",
      description:
        "Индивидуальные консультации психолога в Ростове-на-Дону и онлайн. Тревога, эмоции, самооценка, отношения и сложные жизненные ситуации.",
      keywords: [
        "психолог Ростов-на-Дону",
        "психолог онлайн",
        "консультация психолога",
        "психолог Комсомольская площадь",
        "КПТ психолог",
      ],
      openGraphLocale: "ru_RU",
      openGraphTitle: "Бережно к себе. Шаг за шагом.",
      openGraphDescription: "Психологические консультации очно в Ростове-на-Дону и онлайн.",
      openGraphImage: "/og.png",
      openGraphImageAlt: "Психолог Наталья, очно и онлайн",
      twitterTitle: "Психолог Наталья в Ростове-на-Дону",
      twitterDescription: "Бережная психологическая помощь очно и онлайн.",
    },
    languageSwitcherLabel: "Язык сайта",
    brand: {
      initial: "Н",
      name: "Наталья",
      role: "практикующий психолог",
      homeLabel: "На главную",
    },
    navigation: {
      label: "Основная навигация",
      support: "С чем работаю",
      about: "Обо мне",
      prices: "Стоимость",
      contact: "Записаться",
    },
    hero: {
      eyebrow: "Психолог в Ростове-на-Дону и онлайн",
      titleFirst: "Бережно к себе.",
      titleSecond: "Шаг за шагом.",
      lead: "Помогаю справляться с тревогой, понимать свои эмоции и находить внутреннюю опору в сложные периоды жизни.",
      contact: "Выбрать способ связи",
      approach: "Как проходит работа",
      factsLabel: "Формат консультаций",
      facts: [
        { label: "Формат", value: "Очно и онлайн" },
        { label: "Сессия", value: "60 минут" },
        { label: "Стоимость", value: "от 2 000 ₽" },
      ],
      photoAlt: "Психолог Наталья в кабинете в Ростове-на-Дону",
      quote: "«Важные перемены начинаются с безопасного разговора»",
    },
    support: {
      eyebrow: "С чем можно обратиться",
      title: ["Не обязательно справляться", "со всем в одиночку"],
      lead: "На консультации можно говорить о том, что волнует именно вас. Здесь нет «неправильных» тем или чувств.",
      topics: [
        { number: "01", title: "Тревога и страх", text: "Разберем источники напряжения и найдем способы возвращать себе спокойствие в повседневной жизни." },
        { number: "02", title: "Самооценка и опора на себя", text: "Будем замечать привычные внутренние ограничения и формировать более устойчивое отношение к себе." },
        { number: "03", title: "Сложные периоды", text: "Пройдем через перемены, потери и неопределенность бережно, в вашем темпе и без оценок." },
        { number: "04", title: "Отношения", text: "Поработаем над общением с супругами, детьми, родителями и коллегами, личными границами и взаимопониманием." },
        { number: "05", title: "Эмоциональная регуляция", text: "Освоим практические навыки, которые помогают понимать эмоции, выдерживать их и поддерживать себя." },
        { number: "06", title: "Личностный рост", text: "Проясним ваши ценности и цели, чтобы выбирать решения, которые действительно подходят именно вам." },
      ],
    },
    approach: {
      note: "Безопасное и доверительное пространство, где можно быть собой",
      eyebrow: "Мой подход",
      title: "Понимание вместо готовых советов",
      lead: "Мы вместе исследуем причины сложностей, ваши реакции и привычные сценарии. Затем найдем новые стратегии, которые можно применять в реальной жизни.",
      methods: [
        { number: "01", title: "В вашем темпе", text: "Без давления, оценок и требования быстро измениться." },
        { number: "02", title: "С опорой на науку", text: "Классическая психология и методы когнитивно-поведенческой терапии." },
        { number: "03", title: "С вниманием к практике", text: "Навыки эмоциональной регуляции и самоподдержки между встречами." },
      ],
    },
    about: {
      eyebrow: "Обо мне",
      titleName: "Наталья,",
      titleRole: "практикующий психолог",
      lead: "Считаю, что хорошая терапия начинается с уважения к опыту человека и честного, внимательного контакта.",
      text: "Имею диплом практического психолога ДГПУ. Прошла обучение на клинического психолога в Московском институте психоанализа и продолжаю регулярно повышать квалификацию.",
      education: [
        { label: "Образование", title: "Диплом практического психолога", institution: "ДГПУ" },
        { label: "Повышение квалификации", title: "Профессиональные курсы", institution: "СПб ИДПО" },
        { label: "Дополнительное обучение", title: "Клиническая психология", institution: "Московский институт психоанализа" },
      ],
    },
    prices: {
      eyebrow: "Формат и стоимость",
      title: "Выберите удобный формат",
      lead: "Индивидуальная встреча длится 60 минут. Время согласуем после вашего сообщения.",
      cards: [
        {
          featured: true,
          format: "Онлайн",
          availability: "Из любой точки",
          title: "Онлайн-консультация",
          text: "Разговор через удобный мессенджер в спокойной обстановке.",
          features: ["Индивидуально", "60 минут", "По предварительной записи"],
          price: "2 000 ₽",
          suffix: "за встречу",
          button: "Выбрать онлайн",
        },
        {
          featured: false,
          format: "Очно",
          availability: "Ростов-на-Дону",
          title: "Очная консультация",
          text: "Личная встреча в кабинете в районе Комсомольской площади.",
          features: ["Индивидуально", "60 минут", "Точный адрес после записи"],
          price: "2 500 ₽",
          suffix: "за встречу",
          button: "Выбрать очно",
        },
      ],
    },
    faq: {
      eyebrow: "Вопросы",
      title: "Перед первой встречей",
      items: [
        { question: "Как проходит первая консультация?", answer: "Мы знакомимся, обсуждаем ваш запрос и то, к какому результату вы хотели бы прийти. Вы сможете задать вопросы о формате работы и решить, комфортно ли продолжать." },
        { question: "Можно ли консультироваться онлайн?", answer: "Да. Онлайн-консультация проходит через удобный мессенджер по предварительной договоренности и длится 60 минут." },
        { question: "Где проходят очные встречи?", answer: "В Ростове-на-Дону, в районе Комсомольской площади. Точный адрес сообщается после подтверждения записи." },
        { question: "Как записаться?", answer: "Выберите удобный способ связи: Telegram, WhatsApp, MAX, телефон или Авито. Коротко опишите желаемый формат и время. Наталья ответит и подтвердит встречу по своему расписанию." },
      ],
    },
    contacts: {
      eyebrow: "Первый шаг",
      title: "Выберите удобный способ связи",
      lead: "Напишите, какой формат вам подходит и в какое время удобно встретиться. Наталья ответит на вопросы и подтвердит запись.",
      telegramAria: "Написать Наталье в Telegram",
      whatsappAria: "Написать Наталье в WhatsApp",
      maxAria: "Написать Наталье в MAX",
      phoneAria: "Позвонить Наталье по номеру плюс семь девятьсот пятьдесят один пятьсот шесть сорок шесть пятьдесят девять",
      openDialog: "Открыть диалог",
      openMessenger: "Написать в мессенджере",
      call: "Позвонить",
      avito: "Или написать через объявление на Авито",
    },
    footer: {
      format: ["Очно у Комсомольской площади", "Онлайн по договоренности"],
      legal: "Психологическое консультирование не заменяет медицинскую или экстренную помощь. В ситуации непосредственной угрозы жизни обратитесь по номеру 112.",
      mobileCta: "Выбрать способ связи",
    },
    structuredData: {
      jobTitle: "Практикующий психолог",
      description: "Индивидуальные психологические консультации очно в Ростове-на-Дону и онлайн.",
      city: "Ростов-на-Дону",
      region: "Ростовская область",
      knowsAbout: ["Когнитивно-поведенческая терапия", "Тревога", "Самооценка", "Эмоциональная регуляция", "Семейные отношения"],
    },
  },
  en: {
    locale: "en",
    path: "/en/",
    alternatePath: "/",
    seo: {
      title: "Psychologist Natalya in Rostov-on-Don | In Person and Online",
      description: "Individual psychological counselling in Rostov-on-Don and online for anxiety, emotions, self-esteem, relationships and difficult life situations.",
      keywords: [
        "psychologist Rostov-on-Don",
        "online psychologist",
        "psychological counselling",
        "psychologist Komsomolskaya Square",
        "CBT psychologist",
      ],
      openGraphLocale: "en_US",
      openGraphTitle: "Be gentle with yourself. Step by step.",
      openGraphDescription: "In-person psychological counselling in Rostov-on-Don and online.",
      openGraphImage: "/og-en.png",
      openGraphImageAlt: "Psychologist Natalya, in person and online",
      twitterTitle: "Psychologist Natalya in Rostov-on-Don",
      twitterDescription: "Supportive psychological counselling in person and online.",
    },
    languageSwitcherLabel: "Website language",
    brand: {
      initial: "N",
      name: "Natalya",
      role: "practising psychologist",
      homeLabel: "Home",
    },
    navigation: {
      label: "Main navigation",
      support: "How I can help",
      about: "About me",
      prices: "Fees",
      contact: "Book a session",
    },
    hero: {
      eyebrow: "Psychologist in Rostov-on-Don and online",
      titleFirst: "Be gentle with yourself.",
      titleSecond: "Step by step.",
      lead: "I help you cope with anxiety, understand your emotions and find inner support during difficult periods in life.",
      contact: "Choose how to get in touch",
      approach: "How counselling works",
      factsLabel: "Counselling format",
      facts: [
        { label: "Format", value: "In person and online" },
        { label: "Session", value: "60 minutes" },
        { label: "Fee", value: "from 2,000 ₽" },
      ],
      photoAlt: "Psychologist Natalya in her office in Rostov-on-Don",
      quote: "“Important changes begin with a safe conversation”",
    },
    support: {
      eyebrow: "What you can bring to counselling",
      title: ["You do not have to handle", "everything on your own"],
      lead: "In a session, you can talk about whatever is troubling you. There are no “wrong” topics or feelings here.",
      topics: [
        { number: "01", title: "Anxiety and fear", text: "We will explore the sources of tension and find ways to regain a sense of calm in everyday life." },
        { number: "02", title: "Self-esteem and inner support", text: "We will notice familiar inner limitations and develop a more stable and supportive relationship with yourself." },
        { number: "03", title: "Difficult periods", text: "We will move through change, loss and uncertainty gently, at your pace and without judgement." },
        { number: "04", title: "Relationships", text: "We can work on communication with partners, children, parents and colleagues, as well as personal boundaries and mutual understanding." },
        { number: "05", title: "Emotional regulation", text: "You will learn practical skills for understanding emotions, staying with them and supporting yourself." },
        { number: "06", title: "Personal growth", text: "We will clarify your values and goals so you can make choices that genuinely fit you." },
      ],
    },
    approach: {
      note: "A safe and trusting space where you can be yourself",
      eyebrow: "My approach",
      title: "Understanding instead of ready-made advice",
      lead: "Together, we explore the causes of difficulties, your reactions and familiar patterns. Then we find new strategies that you can use in everyday life.",
      methods: [
        { number: "01", title: "At your pace", text: "Without pressure, judgement or demands for rapid change." },
        { number: "02", title: "Grounded in evidence", text: "Classical psychology and cognitive behavioural therapy methods." },
        { number: "03", title: "Focused on practice", text: "Emotional regulation and self-support skills to use between sessions." },
      ],
    },
    about: {
      eyebrow: "About me",
      titleName: "Natalya,",
      titleRole: "practising psychologist",
      lead: "I believe good counselling begins with respect for each person's experience and honest, attentive contact.",
      text: "I hold a degree in practical psychology from DGPU. I trained in clinical psychology at the Moscow Institute of Psychoanalysis and continue to update my professional qualifications regularly.",
      education: [
        { label: "Education", title: "Degree in Practical Psychology", institution: "DGPU" },
        { label: "Professional development", title: "Professional courses", institution: "SPb IDPO" },
        { label: "Additional training", title: "Clinical Psychology", institution: "Moscow Institute of Psychoanalysis" },
      ],
    },
    prices: {
      eyebrow: "Format and fees",
      title: "Choose the format that suits you",
      lead: "An individual session lasts 60 minutes. We will agree on a time after your message.",
      cards: [
        {
          featured: true,
          format: "Online",
          availability: "From anywhere",
          title: "Online counselling",
          text: "A conversation via a convenient messenger in a calm setting.",
          features: ["Individual", "60 minutes", "By appointment"],
          price: "2,000 ₽",
          suffix: "per session",
          button: "Choose online",
        },
        {
          featured: false,
          format: "In person",
          availability: "Rostov-on-Don",
          title: "In-person counselling",
          text: "A face-to-face session in an office near Komsomolskaya Square.",
          features: ["Individual", "60 minutes", "Exact address after booking"],
          price: "2,500 ₽",
          suffix: "per session",
          button: "Choose in person",
        },
      ],
    },
    faq: {
      eyebrow: "Questions",
      title: "Before your first session",
      items: [
        { question: "What happens in the first session?", answer: "We get to know each other, discuss what brings you to counselling and the outcome you would like to work towards. You can ask questions about the format and decide whether you feel comfortable continuing." },
        { question: "Can I have counselling online?", answer: "Yes. An online session takes place through a convenient messenger by prior arrangement and lasts 60 minutes." },
        { question: "Where do in-person sessions take place?", answer: "In Rostov-on-Don, near Komsomolskaya Square. The exact address is shared after your appointment is confirmed." },
        { question: "How do I book a session?", answer: "Choose a convenient way to contact Natalya: Telegram, WhatsApp, MAX, phone or Avito. Briefly describe your preferred format and time. Natalya will reply and confirm a session according to her schedule." },
      ],
    },
    contacts: {
      eyebrow: "The first step",
      title: "Choose how to get in touch",
      lead: "Send a message with your preferred format and a convenient time. Natalya will answer your questions and confirm the session.",
      telegramAria: "Message Natalya on Telegram",
      whatsappAria: "Message Natalya on WhatsApp",
      maxAria: "Message Natalya on MAX",
      phoneAria: "Call Natalya at plus seven nine five one five zero six four six five nine",
      openDialog: "Open chat",
      openMessenger: "Open messenger",
      call: "Call",
      avito: "Or message through the listing on Avito",
    },
    footer: {
      format: ["In person near Komsomolskaya Square", "Online by arrangement"],
      legal: "Psychological counselling is not a substitute for medical or emergency care. If there is an immediate threat to life, call 112.",
      mobileCta: "Choose how to get in touch",
    },
    structuredData: {
      jobTitle: "Practising psychologist",
      description: "Individual psychological counselling in person in Rostov-on-Don and online.",
      city: "Rostov-on-Don",
      region: "Rostov Region",
      knowsAbout: ["Cognitive behavioural therapy", "Anxiety", "Self-esteem", "Emotional regulation", "Family relationships"],
    },
  },
} as const;

export type SiteContent = (typeof content)[Locale];
